trigger:
- secure

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Test
    jobs:
      - job: UnitTests
        continueOnError: false
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'test'
              projects: '*tests/*Unit/*.csproj'

      - job: IntegrationTests
        continueOnError: false
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'test'
              projects: '*tests/*Integration/*.csproj'

  - stage: Artifacts
    jobs:
      - job: UploadArtifacts
        continueOnError: false
        steps:
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/terraform/'
              artifact: 'terraform-manifests-out'
              publishLocation: 'pipeline'

  - stage: Terraform
    jobs:
      - job: Installer
        continueOnError: true
        steps:
          - task: TerraformInstaller@0
            displayName: Install Terraform
            inputs:
              terraformVersion: 'latest'
          
          - task: TerraformCLI@0
            displayName: Init Terraform
            inputs:
              command: 'init'
              workingDirectory: '$(Pipeline.Workspace)/terraform-manifests-out'
              backendType: 'azurerm'
              backendServiceArm: 'terraform-aks-azurerm'
              backendAzureRmResourceGroupName: 'terraform-storage-rg'
              backendAzureRmStorageAccountName: 'tekkenterraformstorage'
              backendAzureRmContainerName: 'tfstatefiles'
              backendAzureRmKey: 'terraform.tfstate'
              allowTelemetryCollection: true
          - task: TerraformCLI@0
            displayName: Validate Terraform
            inputs:
              command: 'validate'

              workingDirectory: '$(Pipeline.Workspace)/terraform-manifests-out'
              allowTelemetryCollection: true
        
      - job: Deploy
        continueOnError: false
        steps:
         - task: TerraformCLI@0
           inputs:
              command: 'apply'
              workingDirectory: '$(Pipeline.Workspace)/terraform-manifests-out'
              environmentServiceName: 'terraform-aks-azurerm'
              runAzLogin: true
              allowTelemetryCollection: true

      - job: Remove
        continueOnError: false
        steps:
          - task: TerraformCLI@0
            inputs:
              command: 'destroy'

              workingDirectory: '$(Pipeline.Workspace)/terraform-manifests-out'
              environmentServiceName: 'terraform-aks-azurerm'
              runAzLogin: true
              allowTelemetryCollection: true