trigger:
- terraform

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Terraform
    jobs:
      - job: Installer
        continueOnError: false
        steps:
          - task: TerraformInstaller@0
            displayName: Install Terraform
            inputs:
              terraformVersion: 'latest'
          
          - task: TerraformCLI@0
            displayName: Init Terraform
            inputs:
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
              backendType: 'azurerm'
              backendServiceArm: 'terraform-aks-azurerm'
              backendAzureRmResourceGroupName: 'terraform-storage-rg'
              backendAzureRmStorageAccountName: 'tekkenterraformstorage'
              backendAzureRmContainerName: 'tfstatefiles'
              backendAzureRmKey: 'terraform-base.tfstate'
              allowTelemetryCollection: true
          - task: TerraformCLI@0
            displayName: Validate Terraform
            inputs:
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
              allowTelemetryCollection: true