trigger:
- kubernetes

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '545a7676-b6b2-4370-a270-0ba132beb479'
  imageRepository: 'tekkenacr.azurecr.io/characters-api'
  containerRegistry: 'tekkenacr.azurecr.io'
  dockerfilePath: '$src/services/CharactersAPI/Dockerfile'

pool:
  vmImage: ubuntu-latest

stages:
  # - stage: Test
  #   jobs:
  #     - job: UnitTests
  #       continueOnError: false
  #       steps:
  #         - task: DotNetCoreCLI@2
  #           inputs:
  #             command: 'test'
  #             projects: '*tests/*Unit/*.csproj'

  #     - job: IntegrationTests
  #       continueOnError: false
  #       steps:
  #         - task: DotNetCoreCLI@2
  #           inputs:
  #             command: 'test'
  #             projects: '*tests/*Integration/*.csproj'

  - stage: Terraform Validate
    jobs:
      - job: TerraformValidate
        continueOnError: false
        steps:
          - task: PublishPipelineArtifact@1
            displayName: Publish terraform manifests to artifacts
            inputs:
              targetPath: '$(Pipeline.Workspace)/terraform/'
              artifact: 'terraform-manifests-out'
              publishLocation: 'pipeline'
          - task: TerraformInstaller@0
            displayName: Install Terraform
            inputs:
              terraformVersion: 'latest'
          
          - task: TerraformCLI@0
            displayName: Init Terraform
            inputs:
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
              backendType: 'azurerm'
              backendServiceArm: 'terraform-aks-azurerm'
              backendAzureRmResourceGroupName: 'terraform-storage-rg'
              backendAzureRmStorageAccountName: 'tekkenterraformstorage'
              backendAzureRmContainerName: 'tfstatefiles'
              backendAzureRmKey: 'terraform.tfstate'
              allowTelemetryCollection: true
          - task: TerraformCLI@0
            displayName: Validate Terraform
            inputs:
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
              allowTelemetryCollection: true

  - stage: Create AKS Cluster and ACR
    jobs:
      - job: TerraformInit
        steps:
          - task: DownloadSecureFile@1
            displayName: "SSH public key"
            name: sshkey
            inputs:
              secureFile: 'azure-aks.pub'
          - task: TerraformCLI@0
            inputs:
              command: 'init'
              workingDirectory: '$(Pipeline.Workspace)/terraform-manifests-out'
              backendType: 'azurerm'
              backendServiceArm: 'terraform-aks-azurerm'
              backendAzureRmResourceGroupName: 'terraform-storage-rg'
              backendAzureRmStorageAccountName: 'tekkenterraformstorage'
              backendAzureRmContainerName: 'tfstatefiles'
              backendAzureRmKey: 'terraform-dev.tfstate'
              allowTelemetryCollection: false
          
          - task: TerraformCLI@0
            inputs:
              command: 'plan'
              runAzLogin: true
              commandOptions: '-var ssh_public_key=$(sshkey.secureFilePath) -out $(Pipeline.Workspace)/terraform-manifests-out/dev-$(Build.BuildId).out'
              allowTelemetryCollection: false
          
          - task: TerraformCLI@0
            inputs:
              command: 'apply'
              commandOptions: '$(Pipeline.Workspace)/terraform-manifests-out/dev-$(Build.BuildId).out'
              allowTelemetryCollection: true

  - stage: Push to ACR
    displayName: Build Stage
    jobs:
      - job: BuildAndPush
        displayName: Build and Push Job
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: Push To ACR
            inputs:
              containerRegistry: $(containerRegistry)
              repository: $(imageRepository)
              command: 'buildAndPush'
              Dockerfile: $(dockerfilePath)
              buildContext: ''
              tags: |
                $(Build.BuildId)

  - stage: K8SArtifacts
    displayName: K8s artifacts
    jobs:
      - job: Upload
        steps:
          - bash: echo Contents in System Working Dir; ls -R $(System.DefaultWorkingDirectory)
          - bash: echo Contents in Artifact Staging; ls -R $(Build.ArtifactStagingDirectory)
          - task: CopyFiles@2
            displayName: Copy k8s manifests to artifact staging area
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/aks/'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
              OverWrite: true
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifact: 'k8s-manifests'
              publishLocation: 'pipeline'
              
          - bash: echo Contents in System Working Dir; ls -R $(System.DefaultWorkingDirectory)
          - bash: echo Contents in Artifact Staging; ls -R $(Build.ArtifactStagingDirectory)



