# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Tests
    jobs:
      - job: UnitTests
        continueOnError: false
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'test'
              projects: '*tests/*Tests.Unit/*.csproj'
              testRunTitle: 'Unit Tests'
      - job: IntegrationTests
        continueOnError: false
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'test'
              projects: '*tests/*Tests.Integration/*.csproj'
              testRunTitle: 'Integration Tests'
