trigger:
- testk8s

pool:
  vmImage: ubuntu-latest

stages:
  - stage: DeployToAKS
    jobs:
      - job: PushACR
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'tekken-acr-service-connection'
              repository: 'app1/characters-api'
              command: 'buildAndPush'
              Dockerfile: '$(Build.SourcesDirectory)/src/services/CharactersAPI/Dockerfile'
              buildContext: ''
              tags: $(Build.BuildId)
            
          
          - publish: aks
            artifact: aks
          
          - task: Kubernetes@1
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'dev-aks-service-connection'
              namespace: 'dev'
              command: 'apply'
              arguments: '-f aks/characters-mssql-depl.yaml -f aks/characters-mssql-secret.yaml'
              secretType: 'dockerRegistry'
              containerRegistryType: 'Azure Container Registry'

          


